--------------------------------------------------------
--  File created - Thursday-December-07-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTACT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CONTACT" 
   (	"CONTACTNAME" CHAR(30 BYTE), 
	"CONTACTEMAIL" CHAR(50 BYTE), 
	"CONTACTPHONE" CHAR(50 BYTE), 
	"COMPANYNAME" CHAR(30 BYTE), 
	"JOBFUNC" CHAR(255 BYTE), 
	"JOBLEVEL" CHAR(50 BYTE), 
	"INDUSTRY" CHAR(50 BYTE), 
	"EMPLOYEES" CHAR(50 BYTE), 
	"REVENUE" CHAR(50 BYTE), 
	"ZIPCODE" CHAR(5 BYTE), 
	"COUNTRY" CHAR(50 BYTE), 
	"CSTATE" CHAR(50 BYTE), 
	"CITY" CHAR(50 BYTE), 
	"CONTACTID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONTACT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CONTACT_PK" ON "SYSTEM"."CONTACT" ("CONTACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CONTACT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONTACT" MODIFY ("CONTACTID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CONTACT" ADD CONSTRAINT "CONTACT_PK" PRIMARY KEY ("CONTACTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
